# TOKYO TEXTURE SETUP v1.0
# Script pour créer automatiquement la structure de dossiers de textures

import os
import shutil
from pathlib import Path

def create_tokyo_texture_structure():
    """Crée la structure complète de dossiers pour les textures Tokyo"""
    
    base_path = "C:/Users/sshom/Documents/Assets/Textures/Tokyo_Buildings/"
    
    texture_structure = {
        # GRATTE-CIELS
        "skyscrapers": [
            "glass_towers",
            "modern_office", 
            "metallic_facades",
            "corporate_buildings"
        ],
        
        # CENTRES COMMERCIAUX
        "commercial": [
            "shopping_centers",
            "retail_facades",
            "colorful_buildings",
            "modern_stores"
        ],
        
        # IMMEUBLES MOYENS
        "midrise": [
            "apartment_blocks",
            "office_buildings",
            "mixed_use",
            "urban_housing"
        ],
        
        # RÉSIDENTIEL
        "residential": [
            "japanese_houses",
            "modern_homes",
            "traditional_buildings",
            "small_apartments"
        ],
        
        # PETITS BÂTIMENTS
        "lowrise": [
            "small_shops",
            "cafes_restaurants",
            "services",
            "traditional_stores"
        ]
    }
    
    print(f"🗂️ Création structure textures Tokyo dans: {base_path}")
    
    # Créer le dossier de base
    os.makedirs(base_path, exist_ok=True)
    
    # Créer tous les sous-dossiers
    for category, folders in texture_structure.items():
        for folder in folders:
            folder_path = os.path.join(base_path, category, folder)
            os.makedirs(folder_path, exist_ok=True)
            
            # Créer un fichier README avec instructions
            readme_path = os.path.join(folder_path, "README.txt")
            with open(readme_path, 'w', encoding='utf-8') as f:
                f.write(f"📁 DOSSIER DE TEXTURES: {folder.upper()}\n")
                f.write("=" * 50 + "\n\n")
                f.write("🎯 OBJECTIF:\n")
                f.write(f"Textures pour bâtiments de type '{folder}' dans la catégorie '{category}'\n\n")
                f.write("📋 FORMATS SUPPORTÉS:\n")
                f.write("• .jpg, .jpeg (recommandé pour photos)\n")
                f.write("• .png (recommandé pour transparence)\n")
                f.write("• .exr, .hdr (pour HDR)\n")
                f.write("• .tiff, .bmp (autres formats)\n\n")
                f.write("📐 TAILLES RECOMMANDÉES:\n")
                f.write("• Minimum: 512x512 pixels\n")
                f.write("• Optimal: 1024x1024 pixels\n")
                f.write("• Maximum: 4096x4096 pixels\n\n")
                f.write("🏗️ UTILISATION DANS TOKYO ADDON:\n")
                
                if category == "skyscrapers":
                    f.write("• Bâtiments de plus de 50m de hauteur\n")
                    f.write("• Gratte-ciels de zones business\n")
                    f.write("• Façades modernes, vitres, métal\n")
                elif category == "commercial":
                    f.write("• Bâtiments 10-50m de hauteur, largeur >15m\n")
                    f.write("• Centres commerciaux colorés\n")
                    f.write("• Façades commerciales, enseignes\n")
                elif category == "midrise":
                    f.write("• Bâtiments 20-50m de hauteur, largeur <15m\n")
                    f.write("• Immeubles d'appartements\n")
                    f.write("• Bureaux moyens\n")
                elif category == "residential":
                    f.write("• Bâtiments 3-20m de hauteur\n")
                    f.write("• Maisons japonaises modernes\n")
                    f.write("• Petits immeubles résidentiels\n")
                elif category == "lowrise":
                    f.write("• Bâtiments de moins de 10m\n")
                    f.write("• Petits magasins, cafés\n")
                    f.write("• Bâtiments traditionnels\n")
                
                f.write("\n🎨 CONSEILS:\n")
                f.write("• Utilisez des textures seamless (répétables)\n")
                f.write("• Variez les couleurs et styles\n")
                f.write("• Incluez des détails architecturaux\n")
                f.write("• Évitez les textures trop spécifiques\n\n")
                f.write("Generated by Tokyo City Generator Texture System v1.0\n")
            
            print(f"📁 Créé: {folder_path}")
    
    # Créer un fichier de guide principal
    main_guide_path = os.path.join(base_path, "TOKYO_TEXTURE_GUIDE.md")
    with open(main_guide_path, 'w', encoding='utf-8') as f:
        f.write("# 🗾 TOKYO CITY GENERATOR - GUIDE DES TEXTURES\n\n")
        f.write("## 🎯 SYSTÈME DE TEXTURES INTELLIGENT\n\n")
        f.write("Le Tokyo City Generator utilise un système de textures avancé qui sélectionne automatiquement des textures selon:\n")
        f.write("- **Hauteur** du bâtiment\n")
        f.write("- **Largeur** du bâtiment\n")
        f.write("- **Type de zone** (business, commercial, résidentiel)\n\n")
        
        f.write("## 📁 STRUCTURE DES DOSSIERS\n\n")
        for category, folders in texture_structure.items():
            f.write(f"### {category.upper()}\n")
            for folder in folders:
                f.write(f"- `{category}/{folder}/`\n")
            f.write("\n")
        
        f.write("## 🔧 UTILISATION\n\n")
        f.write("1. Placez vos textures dans les dossiers appropriés\n")
        f.write("2. Activez 'Advanced Textures' dans l'addon\n")
        f.write("3. Générez votre ville Tokyo\n")
        f.write("4. Les textures seront automatiquement sélectionnées!\n\n")
        
        f.write("## 📋 CATÉGORIES AUTOMATIQUES\n\n")
        f.write("| Hauteur | Largeur | Catégorie | Dossiers utilisés |\n")
        f.write("|---------|---------|-----------|-------------------|\n")
        f.write("| >50m | - | skyscraper | skyscrapers/* |\n")
        f.write("| 20-50m | >15m | commercial | commercial/* |\n")
        f.write("| 20-50m | ≤15m | midrise | midrise/* |\n")
        f.write("| 10-20m | - | residential | residential/* |\n")
        f.write("| <10m | - | lowrise | lowrise/* |\n\n")
        
        f.write("## 🎨 CONSEILS DE TEXTURING\n\n")
        f.write("- **Utilisez des textures seamless** pour éviter les répétitions visibles\n")
        f.write("- **Variez les styles** dans chaque dossier pour plus de diversité\n")
        f.write("- **Résolution 1024x1024** optimale pour performances/qualité\n")
        f.write("- **Nommage descriptif** pour faciliter l'organisation\n\n")
        
        f.write("Generated by Tokyo City Generator v1.2.0\n")
    
    print(f"\n✅ Structure complète créée!")
    print(f"📁 Dossier principal: {base_path}")
    print(f"📄 Guide: {main_guide_path}")
    print(f"🎯 {sum(len(folders) for folders in texture_structure.values())} dossiers créés")
    
    return base_path

if __name__ == "__main__":
    create_tokyo_texture_structure()
    print("\n🎉 Setup terminé! Vous pouvez maintenant ajouter vos textures dans les dossiers créés.")
